name: upnp
version: 2.0.2+2
description: Universal Plugin and Play Host/Client
homepage: https://git.vivaldigroup.it/yuri.vivaldi/upnp
dependencies:
  xml: ^5.3.1
  crypto: ^3.0.1
  dio: ^4.0.4
environment:
  sdk: ">=2.12.4 <3.0.0"
dev_dependencies:
  test: ^1.20.1
