name: upnp
version: 2.0.1
description: Universal Plugin and Play Host/Client
homepage: https://github.com/YuriVivaldi/upnp
dependencies:
  xml: ^5.1.2
  crypto: ^2.1.5
  dio: ^4.0.4
environment:
  sdk: ">=2.12.3 <3.0.0"
